logging:
  level:
    root: INFO
    com.example.sqsmicro: DEBUG
spring:
  application:
    name: airlines-b
  main:
    allow-bean-definition-overriding: true
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        endpoint: http://elasticmq:9324
      credentials:
        access-key: dummy
        secret-key: dummy
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
scheduler:
  cron-expression: "0 */2 * * * *" # Cada 2 minutos
config:
  server:
    url: http://localhost:8888
app:
  client:
    id: airlines-b
    secret: secret-b-123